[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = auto
markers =
    async_test: marks tests as async (deselect with '-m "not async_test"')
